In [1]:
print("sdjvl")

sdjvl


In [2]:
l =[12,32,4,423,4,234,2]
l


[12, 32, 4, 423, 4, 234, 2]

In [3]:
l.append(233)

In [4]:
l

[12, 32, 4, 423, 4, 234, 2, 233]

In [5]:
l.append(2)

In [6]:
l

[12, 32, 4, 423, 4, 234, 2, 233, 2]

In [49]:
l[::-1]

[2, 233, 234, 4, 4, 32, 12]

In [7]:
l.remove(2)

In [8]:
l

[12, 32, 4, 423, 4, 234, 233, 2]

In [9]:
l.remove(423)

In [10]:
l

[12, 32, 4, 4, 234, 233, 2]

In [11]:
l.remove(232)

ValueError: list.remove(x): x not in list

# List within a list

In [12]:
list1 = []
list1.append(12)
list1.append(1324)
list1.append(34324)
list1

[12, 1324, 34324]

In [20]:
x= []
x.append(list1)


In [21]:
x

[[12, 1324, 34324]]

In [22]:
m = [12,23,23,312,213]
x.append(m)
print(x)

[[12, 1324, 34324], [12, 23, 23, 312, 213]]


In [23]:
t =[]
t.append(x)


In [24]:
t

[[[12, 1324, 34324], [12, 23, 23, 312, 213]]]

In [25]:
t.append([233,2,32,32,3])

In [26]:
t

[[[12, 1324, 34324], [12, 23, 23, 312, 213]], [233, 2, 32, 32, 3]]

In [27]:
t[0]

[[12, 1324, 34324], [12, 23, 23, 312, 213]]

In [28]:
t[-1]

[233, 2, 32, 32, 3]

In [29]:
t[1]

[233, 2, 32, 32, 3]

In [30]:
t[0][0]

[12, 1324, 34324]

# this is how we store a matrix 3x3

In [39]:
m = []
m.append([1,2,3])
m.append([4,5,6])
m.append([7,8,9])

In [40]:
m

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [44]:
m[0]

[1, 2, 3]

In [45]:
m[0][0]

1

In [46]:
m[0][-1]

3

In [48]:
m[-1][-1]

9

In [51]:
m[1][1]

5

In [42]:
for i in m:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9


In [52]:
thislist = list(("apple", "banana", "cherry")) # note the double round-brackets
print(thislist)

['apple', 'banana', 'cherry']


In [53]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[-4:-1])

#Negative indexing means starting from the end of the list.

#This example returns the items from index -4 (included) to index -1 (excluded)

#Remember that the last item has the index -1,


['orange', 'kiwi', 'melon']


In [57]:
import random 
print(random.random())

0.08384407388175119


In [61]:
l = []
l.append(random.random())
l

[0.43506735340952385]

In [62]:
l.append(random.random())
l

[0.43506735340952385, 0.678624154549657]

### append 10 random number in a list 

In [67]:
import random
l =[]
for i in range(10):
     l.append(random.random())
print(l)

[0.38409340143521586, 0.30379520642606106, 0.24477869151599385, 0.9616285152214249, 0.7346758701879958, 0.7878966104914302, 0.9951317783998542, 0.5012326865846634, 0.6482060166704628, 0.2736333397586911]


In [73]:
import random
l =[]
for i in range(109):
     l.append(random.randint(1,10))
print(l)

[3, 9, 4, 1, 3, 7, 5, 9, 2, 3, 1, 8, 9, 10, 3, 9, 7, 5, 3, 5, 4, 9, 3, 10, 9, 4, 6, 2, 4, 9, 7, 10, 8, 5, 10, 2, 10, 5, 9, 1, 9, 2, 2, 7, 6, 4, 1, 9, 10, 2, 1, 1, 7, 3, 7, 4, 8, 10, 6, 10, 2, 5, 6, 10, 4, 6, 9, 2, 9, 8, 10, 8, 6, 7, 9, 4, 7, 6, 6, 10, 4, 10, 5, 8, 10, 10, 6, 3, 3, 4, 9, 8, 8, 6, 4, 8, 8, 7, 8, 2, 6, 3, 10, 7, 5, 10, 4, 6, 4]


In [2]:
import random
l =[]
#initialiase a list with empty 

for i in range(30):
     l.append(random.randint(1,365))
        #append in empty list of 1 to 360
        #append 30 of them
print(l)


[215, 242, 142, 208, 36, 217, 123, 123, 28, 230, 171, 252, 43, 84, 195, 88, 158, 86, 25, 183, 275, 345, 62, 275, 99, 294, 55, 9, 166, 46]


In [3]:
l.sort()
print(l)


[9, 25, 28, 36, 43, 46, 55, 62, 84, 86, 88, 99, 123, 123, 142, 158, 166, 171, 183, 195, 208, 215, 217, 230, 242, 252, 275, 275, 294, 345]


In [78]:
len(l)

30

In [79]:
l[30]

IndexError: list index out of range

In [80]:
l[29]

352

In [81]:
l

[3,
 14,
 32,
 38,
 46,
 60,
 82,
 85,
 102,
 103,
 110,
 130,
 149,
 191,
 199,
 206,
 243,
 249,
 250,
 253,
 253,
 257,
 285,
 301,
 303,
 320,
 325,
 336,
 347,
 352]

### birthday paradox

In [20]:
import random
l =[]
#initialiase a list with empty 

for i in range(30):
     l.append(random.randint(1,365))
        #append in empty list of 1 to 360
        #append 30 of them
l.sort()
print(l)

[9, 15, 18, 19, 33, 43, 43, 57, 88, 97, 104, 116, 137, 147, 149, 157, 159, 203, 204, 210, 221, 230, 236, 258, 266, 290, 305, 312, 314, 326]


In [25]:
i =0
flag = False
while(i < len(l)-1):
    #print(i)
    if(l[i]==l[i+1]):
        flag = True
        break
    i=i+1
if(flag == True):
    print("repeats",l[i])
else:
    print("Not repeats")


repeats 43


In [47]:
import random
l=[]
for i in range(70):
    l.append(random.randint(1,365))
l.sort()
print(l)
i=0
flag = 0
while (i<len(l)-1):
    if(l[i] ==l[i+1]==l[i+2]):
        print("repeat",l[i],l[i+1],l[i+2])
        flag = 1
        break
    i=i+1
if(flag ==0):
    print("not repeats")

[3, 5, 7, 13, 32, 34, 37, 40, 43, 45, 45, 48, 49, 54, 58, 74, 74, 82, 84, 92, 102, 105, 105, 106, 107, 110, 114, 117, 119, 122, 127, 138, 151, 181, 182, 204, 206, 220, 225, 226, 231, 246, 259, 265, 267, 270, 271, 286, 288, 289, 290, 292, 294, 295, 302, 304, 307, 319, 320, 327, 328, 328, 328, 330, 337, 346, 347, 350, 351, 364]
repeat 328 328 328


##
# Naive search 4.4

In [51]:
l = [2,333123,23,423,4,2,1,23,121,]
a = 423
flag =0
for i in range(len(l)-1):
    if(l[i]==a):
        print("hip hip hurray",l[i],a)
        flag =1
        break
if(flag == 0):
    print("not found",a)
    

hip hip hurray 423 423


In [ ]:
l = [2,333123,23,423,4,2,1,23,121,]
a = 423
flag =0
for i in range(len(l)-1):
    if(l[i]==a):
        print("hip hip hurray",l[i],a)
        flag =1
        break
if(flag == 0):
    print("not found",a)

# keep asking the number

In [ ]:
l = [1,21,2,1,2,23,23,4,23,23,2,232,3,332,4,23]

n=0

while (n>-1):
    print("Enter a number type -1 to stop searching")
    n = int(input())
    flag = 0
    for i in range(len(l)-1):
        if(n==l[i]):
            print("hip hip hurra we found ",l[i],n)
            flag =1
            break
    if(flag==0):
        print("not found your number",n)
            

In [4]:
l=[9787768,9876,78,780,87,5,8,1]
l[::-1]

[1, 8, 5, 87, 780, 78, 9876, 9787768]

# obvios sorting 

In [1]:
l = [12,312,32312,21,2,23,2,2,32,32]

a=[] #intializing list

while(len(l)>0):
        min =l[0] #assigning first element in min
        for i in range(len(l)): #iteration from 0 to length of l
            if(min>l[i]):   #comparing wich is bigger if smaller 
                min= l[i]   #replace to min l[i]
        a.append(min)
        l.remove(min)
print(a)
print(l)

[2, 2, 2, 12, 21, 23, 32, 32, 312, 32312]
[]


In [15]:
li = [1,2,1,2,23,2,23,23,4,2]
sum =0
for i in range(len(li)):
    sum = sum +li[i]
print(sum)

83


In [21]:
import random
l=random.sample(list(range(100)),10)
print(l)

[65, 82, 36, 12, 59, 81, 22, 47, 9, 54]


# dot product

In [22]:
l = [12,212,121,521,21]
x = [12,2124,653,35,52]
 
sum =0
for i in range(len(l)):
    sum = sum +l[i]*x[i]
print(sum)

548772


In [27]:
dim =3
r1 = [1,2,3]
r2 = [4,5,6]
r3 =[7,8,9]

s1 = [1,2,3]
s2 = [6,2,3]
s3 = [4,2,1]

A =[]

A.append(r1)
A.append(r2)
A.append(r3)

B = []

B.append(s1)
B.append(s2)
B.append(s3)

print(A)
print(B)

C = [[0,0,0],[0,0,0],[0,0,0]]

for i in range(dim):
    for j in range(dim):
        C[i][j]= A[i][j]+B[i][j]
        print(i,j)
print(C)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [6, 2, 3], [4, 2, 1]]
0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2
[[2, 4, 6], [10, 7, 9], [11, 10, 10]]


#  matrix multiplication


In [28]:
dim =3
r1 = [1,2,3]
r2 = [4,5,6]
r3 =[7,8,9]

s1 = [1,2,3]
s2 = [6,2,3]
s3 = [4,2,1]

A =[]

A.append(r1)
A.append(r2)
A.append(r3)

B = []

B.append(s1)
B.append(s2)
B.append(s3)

print(A)
print(B)

C = [[0,0,0],[0,0,0],[0,0,0]]

for i in range(dim):
    for j in range(dim):
        for k in range(dim):
            C[i][j]= C[i][j]+A[i][k]*B[k][j]
        
print(C)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [6, 2, 3], [4, 2, 1]]
[[25, 12, 12], [58, 30, 33], [91, 48, 54]]


In [44]:
import numpy as np

print('matrix A \n',A,'\n')
print(B,'\n\n')

x = np.mat(A) #converting to numpy matrix
y = np.mat(B) #converting to numpy matrix
 
z = (x*y)  #real matrix multiplication

print(z)

matrix A 
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]] 

[[1, 2, 3], [6, 2, 3], [4, 2, 1]] 


[[25 12 12]
 [58 30 33]
 [91 48 54]]


# notes lists string lists to list

In [50]:
line = '1 2 5 7 5 '
output = line.split(' ')
print(output)

['1', '2', '5', '7', '5', '']


In [55]:
line = '1 2 3 4'
num_str = line.split(' ')       # list of numbers represented as strings
numbers = []                   
for item in num_str:
    numbers.append(int(item))   # convert string to int and append to list
print(numbers)

[1, 2, 3, 4]


In [7]:
line = '12575'
m = int(line)
#list1 = m.split(' ')

numlist = []
for i in m:
    numlist.append(int(i))
print(numlist)

TypeError: 'int' object is not iterable

In [64]:
f = [56,67,75,67899,7]
x = 67
if(x in f):
    print("hi")
else: 
    print("no hi")

hi


In [66]:
L = [ ]
# Enter code below this line #
#		Fill code here       #
# Enter code above this line #
print(L)
# out put[1, 2, 3, 4, 5]

[]


In [68]:
L = []

for i in range(1,6):
    L.append(i)
print(L)

[1, 2, 3, 4, 5]


In [73]:
P = []
P.append(1,2,3,4,5)
P

TypeError: append() takes exactly one argument (5 given)

In [76]:
L= [1,8,5,9,52,85]
Q =L[0:-1]
print(Q)

[1, 8, 5, 9, 52]


In [1]:
L1 = [[12,1212,1],[12,13,3]]
for i in L1:
    print(i)

[12, 1212, 1]
[12, 13, 3]


In [4]:
L1 = [[12,1212,1],[12,

[12, 1212, 1] [12, 1212, 1]
[12, 1212, 1] [12, 13, 3]
[12, 13, 3] [12, 1212, 1]
[12, 13, 3] [12, 13, 3]


In [10]:
L1 = [[[12,1212,1],[12,13,3],[134,65,789]]]
for i in L1:
    for j in i:
        for k in j:
             print(k)

12
1212
1
12
13
3
134
65
789


In [11]:
for i in range(5):
    for j in range(5):
        print(i,j)
        

0 0
0 1
0 2
0 3
0 4
1 0
1 1
1 2
1 3
1 4
2 0
2 1
2 2
2 3
2 4
3 0
3 1
3 2
3 3
3 4
4 0
4 1
4 2
4 3
4 4


In [13]:
l = "1651561653"
x = l.split("5")
print(x)

['16', '1', '616', '3']


In [15]:
a = []
for i in x :
    a.append(int(i))
print(a)

[16, 1, 616, 3]


In [16]:
y ="34678986"
x = int(y)

In [20]:
x+678

34679664

In [19]:
l = [98,789,76]


TypeError: can only concatenate str (not "int") to str

In [22]:
l = [[1,0,0],[0,1,0],[0,0,1]]
sum1 = 0
for i in l:
    for j in l:
        for k in l:
            if(l[j]==l[k])
            

[1, 0, 0]
[0, 1, 0]
[0, 0, 1]


In [28]:
l = [[1,2,3],[7,1,9],[5,7,1]]
sum1 = 1
for i in l:
    for j in i:
         sum1= sum1 *j
print(sum1)

13230


In [33]:
l = [[1,2,3],[7,1,9],[5,7,1]]
#sum1 = 1
for i in l:
    for j in i:
         print(j)

1
2
3
7
1
9
5
7
1


# subsequvence

In [58]:
l1 = [1,2,3,4]
n= len(l1)
for i in range(n):
    for j in range(i,n):
        for k in range(i,j+1):
            print(l1[k],end="")
        print("\n",end="")

1
12
123
1234
2
23
234
3
34
4


In [56]:
l = ['a','b','c','d','e','f','g']

for i in range(len(l)):
    for j in range(i,len(l)):
        for k in range(i,j+1):
            print(l[k],end="")
        print("\n")

a

ab

abc

abcd

abcde

abcdef

abcdefg

b

bc

bcd

bcde

bcdef

bcdefg

c

cd

cde

cdef

cdefg

d

de

def

defg

e

ef

efg

f

fg

g



In [59]:
for i in range(4):
    for j in range(4):
        for k in range(4):
            print(i,j,k)

0 0 0
0 0 1
0 0 2
0 0 3
0 1 0
0 1 1
0 1 2
0 1 3
0 2 0
0 2 1
0 2 2
0 2 3
0 3 0
0 3 1
0 3 2
0 3 3
1 0 0
1 0 1
1 0 2
1 0 3
1 1 0
1 1 1
1 1 2
1 1 3
1 2 0
1 2 1
1 2 2
1 2 3
1 3 0
1 3 1
1 3 2
1 3 3
2 0 0
2 0 1
2 0 2
2 0 3
2 1 0
2 1 1
2 1 2
2 1 3
2 2 0
2 2 1
2 2 2
2 2 3
2 3 0
2 3 1
2 3 2
2 3 3
3 0 0
3 0 1
3 0 2
3 0 3
3 1 0
3 1 1
3 1 2
3 1 3
3 2 0
3 2 1
3 2 2
3 2 3
3 3 0
3 3 1
3 3 2
3 3 3
